export const LOAD_DISCOVER_FILMS = 'LOAD_DISCOVER_FILMS';
export const LOAD_GENRES = 'LOAD_GENRES';
export const DISCOVER_FILMS_SUCCESS = 'DISCOVER_FILMS_SUCCESS';
export const GENRES_SUCCESS = 'GENRES_SUCCESS';
export const DISCOVER_FILMS_ERROR = 'DISCOVER_FILMS_ERROR';
export const GENRES_ERROR = 'GENRES_ERROR';
export const LOAD_SEARCH_FILMS = 'LOAD_SEARCH_FILMS';
export const SEARCH_FILMS_SUCCESS = 'SEARCH_FILMS_SUCCESS';
export const SEARCH_FILMS_ERROR = 'SEARCH_FILMS_ERROR';
export const UPDATE_FORM = 'UPDATE_FORM';
export const LOAD_SELECTED_FILM = 'LOAD_SELECTED_FILM';
export const SELECTED_FILM_SUCCESS = 'SELECTED_FILM_SUCCESS';
export const SELECTED_FILM_ERROR = 'SELECTED_FILM_ERROR';
export const RESET_RESULTS_TO_DEFAULT_STATE =
  'RESET_RESULTS_TO_DEFAULT_STATE';
export const RESET_SELECTED_TO_DEFAULT_STATE =
  'RESET_SELECTED_TO_DEFAULT_STATE';
export const SORT_FILMS_BY = 'SORT_FILMS_BY';
export const RESET_SORTED_BY_TO_DEFAULT_STATE =
  'RESET_SORTED_BY_TO_DEFAULT_STATE';
export const TOTAL_RESULTS = 'TOTAL_RESULTS';
export const IS_LOADING = 'IS_LOADING';
export const IS_LOADING_ERROR = 'IS_LOADING_ERROR';
